### PR TITLE
Revised "advanced" document

### PR DESCRIPTION
**Pull request by sekikn**
* Fixed a function name typo
* Specified the max length of pluginname. I propose 10 characters, because we already know it's safe (e.g., asflicense, checkstyle, shellcheck, whitespace)

### CODE REVIEW

**Comment by sekikn** [comment]
> I propose 10 characters, 

I found longer subsystem names: "tests included" (14 chars), hbaseprotoc, hadoopcheck (11 chars). How long should the max length be?

**Comment by aw-altiscale** [comment]
10 chars sounds reasonable.  It basically comes down to the math that starts in:

https://github.com/aw-altiscale/pre-yetus/blob/413a0755922d866619017b6af1bf017da50bdcc5/precommit/main/test-patch.sh#L2601

The risk is that the comment text may not be wrap correctly. 

We should rename the big ones to something smaller and go for 10 chars as the recommended length.

**Comment by sekikn** [comment]
> We should rename the big ones to something smaller and go for 10 chars as the recommended length.

I agree. What about renaming as follows?

* tests included -> modifytest
* hadoopcheck    -> compat
* hbaseprotoc    -> protoc

**Comment by aw-altiscale** [comment]
I modified 'tests included' to 'test4tests' since I was in the area for another patch. :)

I don't think we should call hbase's protoc check 'protoc'.  I think we'll likely have a protoc-specific test in the future. (ironically, to perhaps test for protoc compatibility so 'compat' is probably also bad.)

I'm tempted to just say let's go for 11 characters instead so we don't have to rename. hah.

**Comment by sekikn** [comment]
OK, I also felt difficult to shorten existing 11 characters. I'll rebase the PR.

**Comment by aw-altiscale** [comment]
Thanks!

**Pull request merged**
